# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc ""
  homepage "https://github.com/efmrl/homebrew-cli"
  version "0.9.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.3/cli2_Darwin_x86_64.tar.gz"
      sha256 "e952878111c4a38bae9c06db5fc720c155c664248ba107fa0d461b5ffcf7e10b"

      def install
        bin.install "efmrl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.3/cli2_Darwin_arm64.tar.gz"
      sha256 "b6b141a9057b0afc8233a63ceba20ba3e204681ac5485d0d9f588ba88d492052"

      def install
        bin.install "efmrl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.3/cli2_Linux_x86_64.tar.gz"
        sha256 "255fa3ae2f42bbc8e2622e99de7748ebb2ef51a4001e05bea5a6ec54b7320c3a"

        def install
          bin.install "efmrl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.3/cli2_Linux_arm64.tar.gz"
        sha256 "94bf338f4646880a327aa93782d4ae33b046580e546972ae85b107d5f3bd876a"

        def install
          bin.install "efmrl"
        end
      end
    end
  end
end
