# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc ""
  homepage "https://github.com/efmrl/homebrew-efmrl-cli"
  version "0.9.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.4/cli2_Darwin_x86_64.tar.gz"
      sha256 "357e3f634d4515bc2bc86f4c2eb81d7eff3b6d630c18407df43df76ae45692d8"

      def install
        bin.install "efmrl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.4/cli2_Darwin_arm64.tar.gz"
      sha256 "f60475114315f5e43e86bce6252644fd56660f5a37f58557a26422e192194291"

      def install
        bin.install "efmrl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.4/cli2_Linux_x86_64.tar.gz"
        sha256 "b7d054a98525c8ed8abddd44116b56db894cb03ba8226f5b99591fe93e1397b1"

        def install
          bin.install "efmrl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.4/cli2_Linux_arm64.tar.gz"
        sha256 "faaca2b2e28a89029023d01081f931ff0df5cdcdd2167d8f649881dcdbd233a7"

        def install
          bin.install "efmrl"
        end
      end
    end
  end
end
