# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli3 < Formula
  desc "CLI for efmrl ephemeral web site hosting"
  homepage "https://github.com/efmrl/cli3"
  version "0.20.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/efmrl/cli3/releases/download/v0.20.0/cli3_Darwin_x86_64.tar.gz"
      sha256 "a5926c854f67d8fc1dc290b7fdcf86098fc2ce3c277813be73ba34df95fe280f"

      define_method(:install) do
        bin.install "efmrl3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/efmrl/cli3/releases/download/v0.20.0/cli3_Darwin_arm64.tar.gz"
      sha256 "fe2fab6f388b22423d457050fe531976ccbdf774145dd04c582c45d69e5302fa"

      define_method(:install) do
        bin.install "efmrl3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/efmrl/cli3/releases/download/v0.20.0/cli3_Linux_x86_64.tar.gz"
      sha256 "7129285db7cfcf543246d8ba776d46f8e2144cbd882873127f1b6d30d473e948"
      define_method(:install) do
        bin.install "efmrl3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/efmrl/cli3/releases/download/v0.20.0/cli3_Linux_arm64.tar.gz"
      sha256 "c0ecb2032197b23ad8c9ce8ed9b237888de76ff895e6d9911671d84d83fccfe3"
      define_method(:install) do
        bin.install "efmrl3"
      end
    end
  end
end
