# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli3 < Formula
  desc "CLI for efmrl ephemeral web site hosting"
  homepage "https://github.com/efmrl/cli3"
  version "0.18.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/efmrl/cli3/releases/download/v0.18.0/cli3_Darwin_x86_64.tar.gz"
      sha256 "cf32b93533221409325bcc12de1ae8eed4bc7c04ffba6b8014590370f55cf8d7"

      define_method(:install) do
        bin.install "efmrl3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/efmrl/cli3/releases/download/v0.18.0/cli3_Darwin_arm64.tar.gz"
      sha256 "986a3a037d23c3299d1ae9aff872910fd4ac41d59d87bc4bc766aef4c069063a"

      define_method(:install) do
        bin.install "efmrl3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/efmrl/cli3/releases/download/v0.18.0/cli3_Linux_x86_64.tar.gz"
      sha256 "afb6438fad949d638fc05298b8f5444bdab6b071bd2befa0333d15d72b3157b7"
      define_method(:install) do
        bin.install "efmrl3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/efmrl/cli3/releases/download/v0.18.0/cli3_Linux_arm64.tar.gz"
      sha256 "02926f251045bc67be5fb9d35d8f9fb7ad743137bae4311bd00cb6555c1fa7d6"
      define_method(:install) do
        bin.install "efmrl3"
      end
    end
  end
end
