# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Efmrl < Formula
  desc ""
  homepage "https://github.com/efmrl/homebrew-cli"
  version "0.9.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.8/cli2_Darwin_x86_64.tar.gz"
      sha256 "338b476eaa5caef00bc6061c57b62a746fb2bf4905047d1817d747265db4a809"

      def install
        bin.install "efmrl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.8/cli2_Darwin_arm64.tar.gz"
      sha256 "3239404a46f9b5d6a0b2b7832baa8b98d6e5581413c11a9ed6599f1bb302e6e9"

      def install
        bin.install "efmrl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.8/cli2_Linux_x86_64.tar.gz"
        sha256 "0538fb982999a6fba27ab21cdc70e5fd808ac9c70309ef07ec229109570e3bf5"

        def install
          bin.install "efmrl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.8/cli2_Linux_arm64.tar.gz"
        sha256 "7a19bd56ebe7d0b26fbce91a526d4573902c34cfe71e5eb6a04a0e1b24198444"

        def install
          bin.install "efmrl"
        end
      end
    end
  end
end
