# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Efmrl < Formula
  desc ""
  homepage "https://github.com/efmrl/homebrew-cli"
  version "0.9.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.11/cli2_Darwin_x86_64.tar.gz"
      sha256 "d01bad62e1c8cf778926bb28c1d43fb62c10fe036252625e3f014a34d8205004"

      def install
        bin.install "efmrl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/efmrl/cli2/releases/download/v0.9.11/cli2_Darwin_arm64.tar.gz"
      sha256 "b6c0f3f7d6efc30e90afb100fc560c7046f6f7fa6618f20028e8b0b01ef74e79"

      def install
        bin.install "efmrl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.11/cli2_Linux_x86_64.tar.gz"
        sha256 "8d3550de9b94a1018c92bdb19fe6abaad727cf2aa76aa74378a2bf8a44a77c5e"

        def install
          bin.install "efmrl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/efmrl/cli2/releases/download/v0.9.11/cli2_Linux_arm64.tar.gz"
        sha256 "024f5df890a062de4361bc604807ff89c69021ef6e66fb8b0dbf810b1cab40a7"

        def install
          bin.install "efmrl"
        end
      end
    end
  end
end
