# This file was generated by GoReleaser. DO NOT EDIT.
cask "efmrl" do
  desc ""
  homepage "https://github.com/efmrl/homebrew-cli"
  version "0.9.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "efmrl"

  on_macos do
    on_intel do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.16/cli2_Darwin_x86_64.tar.gz"
      sha256 "7824b98ca417e94a503e9a2122408033753770aabdc43e305e4bce5489700dde"
    end
    on_arm do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.16/cli2_Darwin_arm64.tar.gz"
      sha256 "95cd57cb25833cb84a50a4fddeaff71128c46e955dca098f278db6c5cf969f76"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.16/cli2_Linux_x86_64.tar.gz"
      sha256 "b16bfbe2303214d2d960656281be3bcd8f3d7a6dbafbeb3a45b7aca043542b58"
    end
    on_arm do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.16/cli2_Linux_arm64.tar.gz"
      sha256 "0bfa6977e058037b4f0e38876526273231f2f7a4900f495db14484b0cd3cde7b"
    end
  end

  # No zap stanza required
end
