# This file was generated by GoReleaser. DO NOT EDIT.
cask "efmrl" do
  desc ""
  homepage "https://github.com/efmrl/homebrew-cli"
  version "0.9.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "efmrl"

  on_macos do
    on_intel do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.18/cli2_Darwin_x86_64.tar.gz"
      sha256 "8cf06acf89405091b9ecaa7855b48f5b58c1c9fd31cba5681728f8ed2298265f"
    end
    on_arm do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.18/cli2_Darwin_arm64.tar.gz"
      sha256 "530e1d2868c8c6616ba46af485aa1c19bbab5185e7ec0589229497749b90771b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.18/cli2_Linux_x86_64.tar.gz"
      sha256 "9bf84e3082adc7bf4b370342d5c95b91fbecc79ea2acf4a2e6334d87517b360c"
    end
    on_arm do
      url "https://github.com/efmrl/cli2/releases/download/v0.9.18/cli2_Linux_arm64.tar.gz"
      sha256 "f9acf6fa7445efe97aec8cc990daa13e41771c555872021e878700929c366639"
    end
  end

  # No zap stanza required
end
